### ISSUE TITLE
move_old_files to their own directory

### ISSUE THREAD

**Issue by turkeyphant** [wolfv6/rclone_jobber#12]
I've followed your example in the thread at https://forum.rclone.org/t/ive-made-a-nice-backup-script-tutorial-for-rclone/4999/9

Here is the job under discussion:

```
source="/home/joti/test_rclone_data/music"
dest="${test_remote}:"
new="music"
move_old_files_to="dated_directory"
#options="--dry-run"
monitoring_URL=""
```

This creates the directory `music` under `test_remote` i.e.` test_remote:/music/files...`

However, any deletions/modifications of these files don't end up under `test_remote:/archive/music/VERSION`

instead they end up under `test_remote:/archive/_VERSION_`

This is problematic because then when I backup with the following script:

```
source="/home/joti/test_rclone_data/docs"
dest="${test_remote}:"
new="docs"
move_old_files_to="dated_directory"
#options="--dry-run"
monitoring_URL=""
```

All my versions of docs are also under `test_remote:/archive/_VERSION_` and I have no idea to tell whether a file came from `/home/joti/test_rclone_data/music` or `/home/joti/test_rclone_data/docs`

How do I use this script to push to a remote that already contains the first version of the files but keep archived versions in their own directories?

**Comment by wolfv6** [comment]
Thank you for bringing this to my attention.  I will take a look this weekend.

**Comment by wolfv6** [comment]
Here is one possible solution.  In rclone_jobber.sh, add $new to backup_dir path, like this:

    if [ "$move_old_files_to" = "dated_directory" ]; then
        # move deleted or changed files to archive/$new/$(date +%Y)/$timestamp directory
        backup_dir="--backup-dir=$dest/archive/$new/$(date +%Y)/$timestamp"

**Comment by turkeyphant** [comment]
Thanks for this. I decided moving forwards it's probably best to be in sync with the latest version you publish. And luckily ```drive``` allows server-side move so I just moved all directories to ```./last_snapshot```.

It's a bit of a shame that each job has its own /archive rather than an overarching one but there we go :)

**Comment by turkeyphant** [comment]
Since the thread on the rclone forum is now closed, please can you elaborate on how "Abort if job is already running (maybe previous run didn’t finish)" is handled?

I looked at the source and there's just a PID check. It doesn't get rescheduled or anything?

**Comment by wolfv6** [comment]
That's right, there's just a PID check and it doesn't get rescheduled.
A backup will be attempted again at the next scheduled back-up time.
If the backup keeps failing, then cron-monitoring service specified by monitoring_URL will notify you.

**Comment by turkeyphant** [comment]
Okay thanks. I left a note on the other issue about the check not seeming to work.

Is there any way to engineer a way to a) make the check more reliable with some sort of flag so that at least it can try again at next schedule or b) even better make it so that only one copy of rclone_jobber can run regardless of which script initiated it?
