### ISSUE TITLE
Errors if $monitoring_URL empty or not provided

### ISSUE THREAD

**Issue by lordslair** [wolfv6/rclone_jobber#5]
Hello,

I noticed that the script fails if a monitoring_URL is provided empty or missing.
I don't use that kind of feature, and I don't think I'm alone

I just added an if test to check if $monitoring_URL is not empty before the wget.
Should work better that way

Commit with fix available here : https://github.com/lordslair/rclone_jobber/commit/7ec95f84095dff08015bac29192a1c874655145c

All the best,

**Comment by wolfv6** [comment]
Thanks. The fix is in release v1.5.2
