### ISSUE TITLE
no cloud backup to local covered

### ISSUE THREAD

**Issue by joschl** [wolfv6/rclone_jobber#6]
The script checks $source with ls and therefore cannot perform any backup from a cloud provider.

**Comment by wolfv6** [comment]
I always assumed $source would be on the local box.
But now that you mention it, backing up something like Google Drive could be useful.

I have not tested $source as a cloud provider.
Does that work if you comment lines 82 to 85?:

    # if source is empty
    if ! ( ls -1qA $source | grep -q . ); then
        print_message "ERROR" "aborted because source is empty."
        exit 1
    fi

**Comment by joschl** [comment]
that is exactly, what I did, to use your script for versioned cloud backups :)
thx btw

**Comment by wolfv6** [comment]
Good.
Please try replacing the conditional on line 82 with this:

    # if source is empty
    if ! ( rclone ls -q $source | grep -q . ); then

Let me know how it works.

**Comment by joschl** [comment]
> Let me know how it works.

works. thx
