### ISSUE TITLE
macOS & Homebrew & pidof: illegal option — o

### ISSUE THREAD

**Issue by Nornode** [wolfv6/rclone_jobber#8]
Running something like:
“pidof -o $PPID -x “$job_name””

causes:
*pidof: illegal option — o* 

rclone_jobber.sh version 1.5.1

pidof -v
pidof version 0.1.4
	Copyright 2003 - 2004 Night Productions

brew -v
Homebrew 2.0.6
Homebrew/homebrew-core (git revision f321f; last commit 2019-03-26)

uname -a
Darwin localhost 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

Are there any alternatives?

**Comment by wolfv6** [comment]
pidof works on Linux.  I don't have a macOS to test on.
Maybe a macOS forum can point you to an alternative.
Please share what you find.

Thanks.
